# Generated by Django 5.0.1 on 2024-01-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massproduct',
            name='mass_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_cooked',
            field=models.IntegerField(default=0),
        ),
    ]
