# Generated by Django 5.0.1 on 2024-01-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_food', '0002_alter_massproduct_mass_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedish',
            name='mass_id',
        ),
        migrations.RemoveField(
            model_name='recipedish',
            name='product_id',
        ),
        migrations.AddField(
            model_name='recipedish',
            name='mass_product_id',
            field=models.ManyToManyField(to='recipe_food.massproduct'),
        ),
    ]
